package com.bhspace.gittest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class aaaa implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String a;

	private java.lang.String aaaa;

	public aaaa() {
	}

	public java.lang.String getA() {
		return this.a;
	}

	public void setA(java.lang.String a) {
		this.a = a;
	}

	public java.lang.String getAaaa() {
		return this.aaaa;
	}

	public void setAaaa(java.lang.String aaaa) {
		this.aaaa = aaaa;
	}

	public aaaa(java.lang.String a, java.lang.String aaaa) {
		this.a = a;
		this.aaaa = aaaa;
	}

}