package com.bhspace.gittest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ddd implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String s1;

	private java.lang.String s2;

	private java.lang.String s3;

	private java.lang.String s4;

	public ddd() {
	}

	public java.lang.String getS1() {
		return this.s1;
	}

	public void setS1(java.lang.String s1) {
		this.s1 = s1;
	}

	public java.lang.String getS2() {
		return this.s2;
	}

	public void setS2(java.lang.String s2) {
		this.s2 = s2;
	}

	public java.lang.String getS3() {
		return this.s3;
	}

	public void setS3(java.lang.String s3) {
		this.s3 = s3;
	}

	public java.lang.String getS4() {
		return this.s4;
	}

	public void setS4(java.lang.String s4) {
		this.s4 = s4;
	}

	public ddd(java.lang.String s1, java.lang.String s2, java.lang.String s3,
			java.lang.String s4) {
		this.s1 = s1;
		this.s2 = s2;
		this.s3 = s3;
		this.s4 = s4;
	}

}