package com.bhspace.gittest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ddd implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String s1;

	private java.lang.String s2;

	public ddd() {
	}

	public java.lang.String getS1() {
		return this.s1;
	}

	public void setS1(java.lang.String s1) {
		this.s1 = s1;
	}

	public java.lang.String getS2() {
		return this.s2;
	}

	public void setS2(java.lang.String s2) {
		this.s2 = s2;
	}

	public ddd(java.lang.String s1, java.lang.String s2) {
		this.s1 = s1;
		this.s2 = s2;
	}

}