package com.bhspace.gittest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class eee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String ss;

	public eee() {
	}

	public java.lang.String getSs() {
		return this.ss;
	}

	public void setSs(java.lang.String ss) {
		this.ss = ss;
	}

	public eee(java.lang.String ss) {
		this.ss = ss;
	}

}