package com.bhspace.gittest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ff implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ff() {
    }




}